config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'chatbox#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :messages, only: [:create]
  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	
	has_many :messages
	has_secure_password

	validates :email, presence: true, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
	validates :username, presence: true, uniqueness: true, length: { maximum: 20 }	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :current_user, :logged_in?

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def logged_in?
		!!current_user 
	end

	def require_user
		if !logged_in?
			flash[:error]=  'You must be log in to perform this action'
			redirect_to login_path
		end
	end
end

app/controllers/chatbox_controller.rb
class ChatboxController < ApplicationController
	before_action :require_user

	def index
		@messages = Message.all.last(20)
	end
	
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :require_user
	
	def create
		message = current_user.messages.build(message_params)
		if message.save
			ActionCable.server.broadcast 'chatroom_channel', mod_message: message_render(message)
		end
	end

	private

	def message_params
		params.require(:message).permit(:body)
	end

	def message_render(message)
		render partial: 'message', locals: { message: message }
	end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	before_action :logged_in_redirect, only: [:new, :create]

	def new
	end
	
	def create
		user = User.find_by(email: params[:session][:email])
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			flash[:success] = 'You have successfully logged in.'
			redirect_to root_path
		else
			flash.now[:error] = 'There was something wrong with your login credentials.'
			render :new
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:success] = 'You have successfully logged out.'
		redirect_to login_path
	end

	private

	def logged_in_redirect
		if logged_in?
			flash[:success] = 'You must be logged in to perform this action.'
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chatbox/index.html.erb
<h4 class="ui center aligned icon header">
  <i class="circular coffee inverted blue icon"></i>
  Say Something
</h4>

<div class="ui grid">
	<div class="twelve wide column">
		<div class="ui card fluid raised chatbox">
			<div class="content" id='messages'>
				<div class="ui feed" id='message-container'>
					<%= render @messages %>
				</div>
			</div>
			<div class="extra content">
				<%= form_for(:message, html: { class: 'ui reply form' }, url: messages_path, remote: true) do |f| %>
			    <div class="field">
			      <div class="ui fluid input icon">
			      	<%= f.text_field :body, placeholder: 'Enter a message...' %>
			      	<%= f.button '<i class="ui blue paper plane icon"></i>'.html_safe %>
			    	</div>
			    </div>
			  <% end %>
			</div>
		</div>
	</div>
	<div class="four wide column">
		<div class="ui card fluid raised chatbox">
			<div class="content">
				<div class="ui inverted vertical menu">
				  <a class="item">
				    Home
				  </a>
				  <a class="item">
				    Messages
				  </a>
				  <a class="item">
				    Friends
				  </a>
				</div>
			</div>
		</div>
		
	</div>
</div>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key,message| %>
  <div class="ui <%= key %> message transition">
    <i class="close icon"></i>
    <div class="header">
      <%= message %>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="ui small inverted menu">
  <div class="ui container">
    <%= link_to "Chatroom", root_path, class: 'item' %>
    <a class="item">
      Messages
    </a>
    <div class="right menu">
      <div class="ui dropdown item">
        Account <i class="dropdown icon"></i>
        <div class="menu">
          <% if logged_in? %>
            <%= link_to :logout, logout_path, method: :delete, class: 'item' %>
          <% else %>
            <%= link_to :login, login_path, class: 'item' %>
            <a class="item">Signup</a>
          <% end %>
        </div>
      </div>
    </div>
    
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'layouts/navigation' %>
    <div class="ui container">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
       <em><%= message.user.username %>: </em> <%= message.body %>
    </div>
  </div>
</div>